import {
  Beat,
  Collection,
  FreeDownloadLead,
  ProducerProfile,
  Promotion,
  SaleRecord,
  StoreSettings,
  BeatPack,
} from '../types';

export const INITIAL_PRODUCER_PROFILE: ProducerProfile = {
  name: 'CASHMERE KID$',
  handle: '@cashmerekid',
  avatarUrl: '/src/assets/images/cashmere_cover_velvet_1790419833792.jpg',
  bannerUrl: '/src/assets/images/cashmere_hero_runway_1790419818906.jpg',
  bio: 'Multi-Platinum & Grammy-Nominated Audio Architect crafting luxury instrumentals for world-tier recording artists. Beats built for the next era.',
  verified: true,
  location: 'Atlanta / Los Angeles / Tokyo',
  socialLinks: {
    youtube: 'https://youtube.com',
    instagram: 'https://instagram.com',
    spotify: 'https://spotify.com',
    twitter: 'https://twitter.com',
    soundcloud: 'https://soundcloud.com',
  },
};

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    name: 'Platinum Vault',
    description: 'Chart-topping high-fashion trap bangers with heavy 808s and brass hits.',
    artworkUrl: '/src/assets/images/cashmere_cover_velvet_1790419833792.jpg',
    beatCount: 4,
    createdDate: '2026-09-01',
  },
  {
    id: 'col-2',
    name: 'Dark Orchestra',
    description: 'Cinematic minor-key bell pads, aggressive drill snares, and gothic string arrangements.',
    artworkUrl: '/src/assets/images/cashmere_cover_vault_1790419848357.jpg',
    beatCount: 4,
    createdDate: '2026-09-15',
  },
];

export const INITIAL_BEATS: Beat[] = [
  {
    id: 'beat-1',
    title: 'VALENTINO VELVET',
    bpm: 142,
    key: 'F# Minor',
    duration: '2:48',
    durationSeconds: 168,
    pricing: {
      mp3Lease: 29.99,
      premiumLease: 79.99,
      unlimited: 199.99,
      exclusive: 999.99,
    },
    freeDownload: true,
    freeDownloadType: 'email_required',
    genre: 'TRAP',
    subGenres: ['Dark Trap', 'Melodic Trap'],
    moods: ['Dark', 'Luxurious', 'Confident'],
    tags: ['cashmere', 'drake', 'future', 'metroboomin', 'trap'],
    artworkUrl: '/src/assets/images/cashmere_cover_velvet_1790419833792.jpg',
    playCount: 184,
    downloadCount: 32,
    likeCount: 56,
    collectionId: 'col-1',
    featured: true,
    releaseDate: '2026-09-20',
    description: 'Heavy 808 bass, dark synth pads, and signature Cashmere Kid voice tag. Engineered for melodic trap verses.',
    voiceTag: true,
    isNew: true,
  },
  {
    id: 'beat-2',
    title: 'TOKYO NIGHTHAWK',
    bpm: 138,
    key: 'C Minor',
    duration: '3:12',
    durationSeconds: 192,
    pricing: {
      mp3Lease: 39.99,
      premiumLease: 89.99,
      unlimited: 249.99,
      exclusive: 1200.0,
    },
    freeDownload: true,
    freeDownloadType: 'email_required',
    genre: 'DARK SYNTH',
    subGenres: ['Cyber Trap', 'Hard Trap'],
    moods: ['Dark', 'Energetic', 'Futuristic'],
    tags: ['travis', '21savage', 'darktrap', 'tokyo', 'cyber808'],
    artworkUrl: '/src/assets/images/cashmere_cover_vault_1790419848357.jpg',
    playCount: 126,
    downloadCount: 22,
    likeCount: 41,
    collectionId: 'col-2',
    featured: true,
    releaseDate: '2026-09-18',
    description: 'Sub-bass distortion meets icy synthesizer Arps. High energy luxury club banger.',
    voiceTag: true,
    isNew: true,
  },
  {
    id: 'beat-3',
    title: 'FREESTYLE ROYALE',
    bpm: 150,
    key: 'G Minor',
    duration: '2:35',
    durationSeconds: 155,
    pricing: {
      mp3Lease: 29.99,
      premiumLease: 79.99,
      unlimited: 199.99,
      exclusive: 850.0,
    },
    freeDownload: true,
    freeDownloadType: 'tagged',
    genre: 'FREESTYLE TRAP',
    subGenres: ['Fast Trap', 'Bounce'],
    moods: ['Hype', 'Fast', 'Bouncy'],
    tags: ['freestyle', 'gunna', 'lilbaby', 'banger', 'flp'],
    artworkUrl: '/src/assets/images/cashmere_cover_velvet_1790419833792.jpg',
    playCount: 94,
    downloadCount: 18,
    likeCount: 29,
    collectionId: 'col-1',
    featured: false,
    releaseDate: '2026-09-15',
    description: 'Ultra bouncy 150 BPM freestyle canvas with crisp hi-hat rolls and sharp 808 snaps.',
    voiceTag: true,
  },
  {
    id: 'beat-4',
    title: 'CARTIER DYNASTY',
    bpm: 132,
    key: 'A# Minor',
    duration: '2:55',
    durationSeconds: 175,
    pricing: {
      mp3Lease: 49.99,
      premiumLease: 99.99,
      unlimited: 299.99,
      exclusive: 1500.0,
    },
    freeDownload: false, // Disabled per beat toggle example
    freeDownloadType: 'email_required',
    genre: 'HARD TRAP',
    subGenres: ['Brass Trap', 'Orchestral Trap'],
    moods: ['Triumphant', 'Aggressive', 'Majestic'],
    tags: ['cartier', 'youngthug', 'brass', 'platinum', 'cashmerekid'],
    artworkUrl: '/src/assets/images/cashmere_cover_vault_1790419848357.jpg',
    playCount: 148,
    downloadCount: 0,
    likeCount: 52,
    collectionId: 'col-2',
    featured: true,
    releaseDate: '2026-09-12',
    description: 'Lavish orchestral horn stabs paired with booming Atlanta style sub frequencies.',
    voiceTag: true,
  },
  {
    id: 'beat-5',
    title: 'NEON MAYBACH',
    bpm: 140,
    key: 'E Minor',
    duration: '3:05',
    durationSeconds: 185,
    pricing: {
      mp3Lease: 34.99,
      premiumLease: 84.99,
      unlimited: 220.0,
      exclusive: 950.0,
    },
    freeDownload: true,
    freeDownloadType: 'email_required',
    genre: 'TRAP',
    subGenres: ['Smooth Trap', 'Midnight Trap'],
    moods: ['Atmospheric', 'Chilled', 'Luxurious'],
    tags: ['maybach', 'rickross', 'smooth', 'synth', 'cashmere'],
    artworkUrl: '/src/assets/images/cashmere_cover_velvet_1790419833792.jpg',
    playCount: 82,
    downloadCount: 15,
    likeCount: 24,
    collectionId: 'col-1',
    featured: false,
    releaseDate: '2026-09-08',
    description: 'Smooth analog synth chords with deep sliding 808 glides. Luxury night cruise beat.',
    voiceTag: true,
  },
  {
    id: 'beat-6',
    title: 'EMPIRE STATE FREESTYLE',
    bpm: 145,
    key: 'D Minor',
    duration: '2:40',
    durationSeconds: 160,
    pricing: {
      mp3Lease: 29.99,
      premiumLease: 79.99,
      unlimited: 199.99,
      exclusive: 899.99,
    },
    freeDownload: true,
    freeDownloadType: 'tagged',
    genre: 'DRILL',
    subGenres: ['East Coast Trap', 'Drill Trap'],
    moods: ['Gritty', 'Hard', 'Relentless'],
    tags: ['freestyle', 'popmoke', 'fivio', 'drill', 'empire'],
    artworkUrl: '/src/assets/images/cashmere_cover_vault_1790419848357.jpg',
    playCount: 105,
    downloadCount: 19,
    likeCount: 31,
    collectionId: 'col-2',
    featured: false,
    releaseDate: '2026-09-05',
    description: 'Fast cadence sliding bass with hyper snares. Created for non-stop rap cyphers.',
    voiceTag: true,
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    code: 'CASHMERE50',
    discountPercent: 50,
    active: true,
    usageCount: 0,
    expirationDate: '2026-12-31',
    description: '50% OFF All Non-Exclusive Leases for VIP Artist Members',
  },
];

// Clean zero-state arrays for real transaction history (NO fake sales or fake customers!)
export const INITIAL_SALES_RECORDS: SaleRecord[] = [];
export const INITIAL_FREE_DOWNLOAD_LEADS: FreeDownloadLead[] = [];

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  currency: 'USD',
  currencySymbol: '$',
  storeName: 'CASHMERE KID$',
  customDomain: 'cashmerekid.com',
  stripeConnected: true,
  paypalConnected: true,
  requireEmailForFreeDownload: true,
  voiceTagFrequencySeconds: 15,
  autoSendInvoices: true,
};

export const INITIAL_BEAT_PACKS: BeatPack[] = [
  {
    id: 'pack-1',
    name: 'CASHMERE VAULT SESSIONS VOL. 1',
    description: 'The ultimate luxury trap collection. Contains three world-tier uncompressed beat files with full MP3 licensing rights.',
    price: 49.99,
    artworkUrl: '/src/assets/images/cashmere_cover_velvet_1790419833792.jpg',
    beatIds: ['beat-1', 'beat-2', 'beat-4'],
    freeDownload: false,
    published: true,
    createdDate: '2026-09-21',
  },
  {
    id: 'pack-2',
    name: 'STREET WEAR & DRILL PACK (FREE)',
    description: 'High energy fast-paced drill and trap outlines. Available as a complimentary gift for VIP recording artists.',
    price: 0,
    artworkUrl: '/src/assets/images/cashmere_cover_vault_1790419848357.jpg',
    beatIds: ['beat-3', 'beat-5', 'beat-6'],
    freeDownload: true,
    published: true,
    createdDate: '2026-09-22',
  }
];
