import { LicenseTierInfo, LicenseTierKey } from '../types';

export const LICENSE_TIERS: Record<LicenseTierKey, LicenseTierInfo> = {
  mp3Lease: {
    key: 'mp3Lease',
    name: 'MP3 Lease',
    price: 29.99,
    format: '320kbps Tagless MP3',
    audioStreams: '100,000 Streams',
    videoStreams: '1 Commercial Music Video',
    radioStations: '2 Radio Stations',
    performances: 'Non-profit / Small Venues',
    stemsIncluded: false,
    royaltySplit: '100% Artist Keeps Earnings',
    description: 'Great for independent singles, mixtapes, and soundcloud releases.',
  },
  premiumLease: {
    key: 'premiumLease',
    name: 'M4A Premium Lease',
    price: 79.99,
    format: 'High-Fidelity M4A / AAC + MP3',
    audioStreams: '500,000 Streams',
    videoStreams: '2 Commercial Music Videos',
    radioStations: '10 Radio Stations',
    performances: 'Paid Shows up to 2,000 Capacity',
    stemsIncluded: false,
    royaltySplit: '100% Artist Keeps Earnings',
    description: 'Ideal for major streaming platforms (Spotify, Apple Music) with pristine studio audio.',
    popular: true,
  },
  unlimited: {
    key: 'unlimited',
    name: 'Unlimited Stems Lease',
    price: 199.99,
    format: 'Full Trackout Stems (M4A) + MP3',
    audioStreams: 'UNLIMITED Streams',
    videoStreams: 'UNLIMITED Videos',
    radioStations: 'UNLIMITED Radio Play',
    performances: 'UNLIMITED Paid Performances',
    stemsIncluded: true,
    royaltySplit: '100% Artist Keeps Earnings',
    description: 'Includes individual audio stems for full studio mix/mastering flexibility.',
  },
  exclusive: {
    key: 'exclusive',
    name: 'Full Exclusive Rights',
    price: 999.99,
    format: 'Full Trackout Stems + Master M4A + Project Stems',
    audioStreams: 'UNLIMITED (Owned Exclusively)',
    videoStreams: 'UNLIMITED Commercial Sync',
    radioStations: 'Worldwide Radio & TV Rights',
    performances: 'Worldwide Arenas & Tours',
    stemsIncluded: true,
    royaltySplit: '100% Full Ownership Transfer',
    description: 'Beat is permanently removed from the store. You own full master rights.',
  },
};
